### ISSUE TITLE
just can't open the app

### ISSUE THREAD

**Issue by solarhell** [yaqinking/DMHY#1]
I hava reinstall the app,but still can't run.I also tried to turn off the macOS security$privacy options.So do i need to build by myself?

**Comment by yaqinking** [comment]
I have been signed this application as identified developers.

Check your `System Preferences.app` -> `Security & Privacy` tab, If `Allow apps downloaded from:` is `Mac App Store` , Change it to `Mac App Store and identified developers.`

If you used previous version less than 1.5.7 it maybe database crashed (The 1.5.7 version data migrate process will as normaly worked.), use [AppClear](https://freemacsoft.net/appcleaner/) remove database related file.
![image](https://cloud.githubusercontent.com/assets/6315031/16937969/26cd6502-4da6-11e6-8e5a-522108444718.png) 

Then reopen this app.

**Comment by solarhell** [comment]
Thank you.I just set `Allow apps downloaded from:` to `any source`,and i used the AppClear,but it just deleted the whole app without other folders.I still can't open it with a dialog popped `Application DMHY can't open`.

**Comment by solarhell** [comment]
BTW, i'm using macOS 10.11.6.

**Comment by yaqinking** [comment]
I install a new virtual machine ( 10.11.6 ), It just works.
Waiting for more test info.
